#build docker image and push to ecr
#added paths-ignore to not trigger the pipe every single push 
name: Docker Build and Push

on:
  push:
    branches:
      - main
    paths-ignore: 
      - 'README.md'
      - 'screenshots/**'
      - '*.png'
  workflow_dispatch:

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: it-tools
  AWS_ACCOUNT_ID: 305476115260

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: checkout code 
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker image
      run: docker build --platform linux/amd64 -t ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }} .
   
    - name: push image to ecr 
      run: docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}


        
